spring:
  application.name: wallet-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect

  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

